### PR TITLE
09 Specs and N+1 problem

### PR DESCRIPTION
**Pull request by Alejandroq12**
Hello, dear reviewer.

#### n+1
- Made sure that the N+1 problem is solved when fetching all posts and their comments for a user.
    - Did not use the bullet gem in this exercise - instead analyzed the logs as showed in this [article](https://dev.to/junko911/rails-n-1-queries-and-eager-loading-10eh)
    - **Included the screenshots of my app's logs before and after the fix**
 
Before solving N + 1 problem
Screenshot from 2024-01-29 23-19-19

After solving N + 1 problem
Screenshot from 2024-01-29 23-21-59

#### Integration specs
- Used Capybara to write integration tests for each view in my project.
- Thought on the flow of things and group the tests of page in a way that makes sense. For example, one test would check for the things in the page and another test for clicking links on it.

- User index page:
  - I can see the username of all other users.
  - I can see the profile picture for each user.
  - I can see the number of posts each user has written.
  - When I click on a user, I am redirected to that user's show page.

- user show page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see the user's bio.
  - I can see the user's first 3 posts.
  - I can see a button that lets me view all of a user's posts.
  - When I click a user's post, it redirects me to that post's show page.
  - When I click to see all posts, it redirects me to the user's post's index page.

- User post index page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see a post's title.
  - I can see some of the post's body.
  - I can see the first comments on a post.
  - I can see how many comments a post has.
  - I can see how many likes a post has.
  - I can see a section for pagination if there are more posts than fit on the view.
  - When I click on a post, it redirects me to that post's show page.

- Post show page:
  - I can see the post's title.
  - I can see who wrote the post.
  - I can see how many comments it has.
  - I can see how many likes it has.
  - I can see the post body.
  - I can see the username of each commentor.
  - I can see the comment each commentor left.

Run only integration tests:
```
rspec spec/system
```
All tests are passing:
[Video of tests passing](https://github.com/Alejandroq12/juliodev-blog/assets/95459740/99473a40-8a9d-4fad-8766-fb3a397e2ad1)

### **Please, take into account that in order to run the project you have to rename the .env.example file to .env and fill all fields with the right port, database username, database password, host, port (Rails port), and database port.**

Thank you. I hope you have a great day.

### CODE REVIEW

**Comment by Reem-lab** [comment]
@Alejandroq12 could you check your slack?

**Comment by Alejandroq12** [comment]
Hi, sure. I will chek it now.

**Review by Reem-lab — APPROVED** [review]
# Hi Team,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights

- [ ]  Descriptive issues ⭐
- [ ]  Kanban setup well ⭐
- [ ] Test are passed 💪🏻
- [ ] Great job working on the tests🔥🔥



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Alejandroq12** [comment]
Thank you very much for your time and valuable feedback.

**Pull request merged**
