### PR TITLE
07 forms

### PR DESCRIPTION
**Pull request by Alejandroq12**
Hello, dear reviewer.
I made sure to meet all requirements. But because i was running out of time I did no styled the forms and there are some minor adjustments that I must made that are not related directly with the requirements. Thank you very much for your understanding and have a great day.

### Project requirements
-  Create a method called `current_user` in your ApplicationController to make current user data available to all controllers.
    -  It will return the first user from the database.
    -  Don't worry about proper authentication at this time. You will add it in the upcoming projects.
- Create forms to perform the following functions:
    - Creates a Post on behalf of the `current_user` (use the method that you created in your ApplicationController).
    - Create a comment on behalf of the `current_user` (use the method that you created in your ApplicationController).
- Allow Users to add likes to Posts.

In this view you will be able to create a new comment and to like a post.
The ids may be diferent.
http://127.0.0.1:3000/users/3/posts/7
Screenshot from 2024-01-20 22-26-29
To add a post you can do it in the main page:
image
According to requirements the post gets added for the first user because I believe that in the future it will be a requirement to select the user from the current session:
Screenshot from 2024-01-20 22-52-53

### **Please, take into account that in order to run the project you have to rename the .env.example file to .env and fill all fields with the right port, database username, database password, host, port (Rails port), and database port.**

Thank you. I hope you have a great day.

### CODE REVIEW

**Review by zieeco — CHANGES_REQUESTED** [review]
Hi @Alejandroq12 ,






Great so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- Nice project.✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._

- [x] I could only see a form for adding comments, and like, I couldn't find any for creating a post. Is this an oversight from my end? Please, double-check to fix this.





## Optional suggestions

- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Alejandroq12** [comment]
Hello, the one for creating a post is in the main page, sorry. It was my fault because without css it is not very visible.

**Comment by Alejandroq12** [comment]
image

**Comment by Alejandroq12** [comment]
image

**Comment by zieeco** [comment]
I'm deeply sorry, I see it now. Please, submit again

**Comment by Alejandroq12** [comment]
Do not worry, I completely understand that it was my fault because It could have been better to style it but I was running out time.
Thank you for your time.

**Review by zieeco — APPROVED** [review]
> Hi @Alejandroq12 ,
> 
 # STATUS: APPROVED! 🥇 💯
 Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
 
 done [ done ](https://camo.githubusercontent.com/b4c0acec224b4b51eccd1e89daa9d73d3e66faca2da46937ed18182b9db03c0d/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f61356c6c6864574b4d4f49666e654d4370422f67697068792e676966) [ ](https://camo.githubusercontent.com/b4c0acec224b4b51eccd1e89daa9d73d3e66faca2da46937ed18182b9db03c0d/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f61356c6c6864574b4d4f49666e654d4370422f67697068792e676966)

 ## Highlights
* Great job, your project is error free 👍
 * Nice work you meet all the requirements 🥇
 * All linters passed ✔️

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

 Good luck! 🎉

 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Alejandroq12** [comment]
Thank you very much for you valuable time. Have a good day or night depending of your time zone.

**Pull request merged**
